application: mikesnflpool
version: 1
runtime: go
api_version: go1

handlers:
- url: /api/.*
  script: _go_app
  # secure: always

- url: /bower_components/*
  static_dir: client/dist/bower_components
  # secure: always

- url: /images/*
  static_dir: client/dist/images
  # secure: always

- url: /scripts/*
  static_dir: client/dist/scripts
  # secure: always

- url: /styles/*
  static_dir: client/dist/styles
  # secure: always

- url: /views/*
  static_dir: client/dist/views
  # secure: always

- url: /.*
  static_files: client/dist/index.html
  upload: client/dist/index.html
  # secure: always

skip_files:
  # - ^(.*/)?#.*#
  # - ^(.*/)?.*~
  # - ^(.*/)?.*\.py[co]
  # - ^(.*/)?.*/RCS/.*
  # - ^(.*/)?\..*
  - (client/node_modules/.*)
  - (client/test/.*)
  - (client/app/.*)
  - (client/bower_components/.*)